browser=chrome
baseURL=https://api.twitter.com/2
bearertoken=AAAAAAAAAAAAAAAAAAAAAEEr5wEAAAAAlw0ZZ5derzSujO5XijTXmTxh0Fc%3DOSqAyVHJiiOrGixPWqaaMlftaj3MjeoJDGiiMP3ikj6ouczCPI
username=paulsankalan
tweetID=1996509658564239570